version: '3.2'

services:
    db:
      image: postgres:13.2
      container_name: query_store_postgres
      shm_size: 256m
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=query_store
        - POSTGRES_PASSWORD=supersecret
      volumes:
        - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./docker/data/postgres:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U query_store"]
        interval: 30s
        retries: 3
